### ISSUE TITLE
Connecting

### ISSUE THREAD

**Issue by MGW14** [Ultrapowa/ucs#3]
Hello,
i successfully started the server. how do i connect to it. (bluestack/windows/ios/android, whatever)
thanks

**Comment by MikeMart77** [comment]
Make a hosts entry pointing gamea.clashofclans.com (android) or game.clashofclans.com (iOS) to the IP address of your server.

On android, you can use an app like MyselfGod's Hosts Go, which lets you set hosts using a VPN, and therefore requires no root.

**Comment by jeanbmar** [comment]
You will also need the right old game client version that works with this old server
